### ISSUE TITLE
Error: Xrm Context is not available. 

### ISSUE THREAD

**Issue by sourav-prescriber-360** [AleksandrRogov/DynamicsWebApi#26] opened 2018-04-04 18:14 UTC
Getting this Error while making 
```
dynamicsWebApi.retrieveAllRequest(request).then(function (response) {
        console.log(request);
        var records = response.value;
        console.log(records);
        //do something else with a records array. Access a record: response.value[0].subject;
    })
    .catch(function (error){
        //catch an error
        console.log(error);
    });
```
```
Error: Xrm Context is not available. In most cases, it can be resolved by adding a reference to a ClientGlobalContext.js.aspx. Please refer to MSDN documentation for more details.
    at getXrmContext (/Users/beingsrv/Desktop/node-api/node_modules/dynamics-web-api/lib/utilities/Utility.js:34:11)
    at getClientUrl (/Users/beingsrv/Desktop/node-api/node_modules/dynamics-web-api/lib/utilities/Utility.js:38:19)
    at Object.initWebApiUrl (/Users/beingsrv/Desktop/node-api/node_modules/dynamics-web-api/lib/utilities/Utility.js:53:12)
    at DynamicsWebApi.setConfig (/Users/beingsrv/Desktop/node-api/node_modules/dynamics-web-api/lib/dynamics-web-api.js:139:49)
    at Object.exports.GetAllRecords (/Users/beingsrv/Desktop/node-api/app/httpRequest/httpGet.js:22:20)
    at /Users/beingsrv/Desktop/node-api/server.js:54:13
    at Layer.handle [as handle_request] (/Users/beingsrv/Desktop/node-api/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/beingsrv/Desktop/node-api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/beingsrv/Desktop/node-api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/beingsrv/Desktop/node-api/node_modules/express/lib/router/layer.js:95:5)
    at /Users/beingsrv/Desktop/node-api/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/beingsrv/Desktop/node-api/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/beingsrv/Desktop/node-api/node_modules/express/lib/router/index.js:275:10)
    at /Users/beingsrv/Desktop/node-api/server.js:45:2
    at Layer.handle [as handle_request] (/Users/beingsrv/Desktop/node-api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/beingsrv/Desktop/node-api/node_modules/express/lib/router/index.js:317:13)
```

**Comment by AleksandrRogov** [comment] 2018-04-04 18:52
Hi @sourav-prescriber-360 ,
What configuration did you provide for the DynamicsWebApi? When you use it in Node.js you need to provide `webApiUrl`. For example:

```js
var dynamicsWebApi = new DynamicsWebApi({ 
    webApiUrl: 'https:/myorg.api.crm.dynamics.com/api/data/v9.0/',
    onTokenRefresh: acquireToken
});
```

**Comment by AleksandrRogov** [comment] 2018-04-05 19:49
Duplicate of #15

**Closed by AleksandrRogov** 2018-04-05 19:49 UTC
Labels: duplicate
