### ISSUE TITLE
When requests exceed 2000 chars an array is returned

### ISSUE THREAD

**Issue by Suxsem** [AleksandrRogov/DynamicsWebApi#81] opened 2020-11-26 16:42 UTC
I understand that when a request exceed 2000 characters is automatically transformed into a batch request, howevere the response is an array which the first object is the actual response.

At the moment I'm using this strategy for my fetches:

```
return dynamicsWebApi.fetch("products", fetch).then((results) => {
      return Array.isArray(results) && results.length > 0 ? results[0] : results;
    });
```

I think it may be useful to automatically do that at the library level

**Comment by AleksandrRogov** [comment] 2020-11-28 20:18
@Suxsem could not reproduce it. Both times the response was an object and the results were inside a `response.value` array. I ran the following requests:

```js
const fetchXml = '<fetch mapping="logical" output-format="xml-platform" version="1.0" distinct="false">' +
	'<entity name="account">' +
	'<attribute name="accountid"/>' +
	'<attribute name="name"/>' +
	'</entity>' +
	'</fetch>';

const response = await dynamicsWebApi.fetch("accounts", fetchXml);
//response is an Object, and results are inside a response.value array
const resultsArray = response.value;

const fetchXml2 = '<fetch mapping="logical" output-format="xml-platform" version="1.0" distinct="false">' +
	'<entity name="account">' +
	'<attribute name="accountid"/>';

for (let i = 0; i < 200; i++) {
	fetchXml2 += '<attribute name="name"/>';
}

fetchXml2 += '</entity>' +
	'</fetch>';

const response2 = await dynamicsWebApi.fetch("accounts", fetchXml2);
//response2 is an Object, and results are inside a response2.value array
const resultsArray2 = response2.value;
```

**Comment by AleksandrRogov** [comment] 2020-11-28 20:43
@Suxsem ok, it seems like this issue is related to the one that you reported here #80. something goes wrong when the requests run in parallel.

**Comment by AleksandrRogov** [comment] 2020-11-28 22:20
Closing this one, because it's directly related to #80

**Closed by AleksandrRogov** 2020-11-28 22:20 UTC
Labels: under investigation
